server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ATTENDANCE-SERVICE
          uri: lb://ATTENDANCE-SERVICE
          predicates:
          - Path=/attendance/**
        - id: BOOK-SERVICE
          uri: lb://BOOK-SERVICE
          predicates:
          - Path=/books/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/departments/**
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
          - Path=/employees/**
        - id: LEAVE-SERVICE
          uri: lb://LEAVE-SERVICE
          predicates:
          - Path=/leaves/**
    